plugins {
    id 'java'
    id 'org.jetbrains.intellij.platform' version '2.6.0'
}

version = project.version
def javaRelease = providers.gradleProperty('javaVersion').get().toInteger()

repositories {
    mavenCentral()

    intellijPlatform {
        defaultRepositories()
    }
}

dependencies {
    implementation group: 'org.apache.directory.api', name: 'api-all', version: apacheDirectoryApiVersion

    intellijPlatform {
        local idePath
        instrumentationTools()
        pluginVerifier()
    }
}

sourceSets {
    main {
        java.srcDirs 'src'
        resources.srcDirs 'resources'
    }
}

intellijPlatform {
    pluginConfiguration {
        name = 'LDAP browser'
        version = project.version

        ideaVersion {
            sinceBuild = '261'
            untilBuild = '261.*'
        }
    }

}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = javaRelease
}
